name = "CraftNectar"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc7852310f7dc93bf280a337fc8961dbb255af393f7784487e26161a719b3884"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
